#if !canImport(ObjectiveC)
import XCTest

extension FutureKeepTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FutureKeepTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FutureKeepTests.__allTests__FutureKeepTests),
    ]
}
#endif
